# Generated by Django 4.2.5 on 2023-09-17 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('owner', models.CharField(default='default_model', max_length=100)),
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default_name', max_length=100)),
                ('model_name', models.CharField(default='default_model', max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('status', models.BooleanField(default=False)),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True)),
                ('imei_number', models.CharField(blank=True, max_length=15, null=True)),
                ('device_type', models.CharField(blank=True, max_length=50, null=True)),
                ('os_version', models.CharField(blank=True, max_length=50, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('firmware_version', models.CharField(blank=True, max_length=100, null=True)),
                ('storage_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('ram_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('cpu_info', models.CharField(blank=True, max_length=100, null=True)),
                ('is_wireless', models.BooleanField(default=True)),
                ('wireless_protocols', models.CharField(blank=True, max_length=100, null=True)),
                ('battery_status', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
