# Generated by Django 4.2.5 on 2023-09-17 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_remove_device_name_device_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.PositiveIntegerField(blank=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
