# Generated by Django 4.2.5 on 2023-10-10 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_mqttmessage_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='mqttmessage',
            name='is_base64_encoded',
            field=models.BooleanField(default=False),
        ),
    ]
